### ISSUE TITLE
Release Workflow

### ISSUE THREAD

**Issue by sswastik02** [mathworks/mjssetup#1]
Set up a GitHub Actions workflow to automate the release process for this package, ensuring it is easily accessible to users directly from GitHub.

**Comment by sswastik02** [comment]
@hannahpullen,
If this issue seems valid to you, I would like to work on this.

**Comment by hannahpullen** [comment]
I already have plans to automate the release, so I can work on this

**Comment by hannahpullen** [comment]
Added GitHub actions workflow: https://github.com/mathworks/mjssetup/releases/tag/v1.1.0
